/* 
 *  Copyright (c) 2012-2015, Inspirock Corporation.
 *  All rights reserved.
 */

/* 
 *  Copyright (c) 2012-2014, Inspirock Corporation.
 *  All rights reserved.
 */

/* 
 *  Copyright (c) 2012-2017, Inspirock Corporation.
 *  All rights reserved.
 */

define("modules/lazyload",["jquery"],function(){function i(a){var c=new window.Image;c.onload=function(){a.is("img")?a.attr("src",a.data("url")):a.css("background-image","url('"+a.data("url")+"')")};c.src=a.data("url");b=b.add(a)}function d(){if(a.length){var b=c.scrollTop(),g=b+c.height();a=$($.grep(a,function(a){var a=$(a),c=a.offset().top;return c+a.height()>=b-e&&c<=g+e?(i(a),!1):!0}))}}function g(e){e.onscroll?(a=$(".lazyload").not(b),d(),c.off("scroll.ll resize.ll").on("scroll.ll resize.ll",
d)):$(".lazyload").not(b).not(a).each(function(){i($(this))})}var j={},b=$(),a=$(),c=$(window),e=50;j.initialize=function(a){a=a||{};if("complete"===document.readyState)g(a);else $(window).on("load",function(){g(a)})};return j});
define("modules/dock",["modules/events","jquery"],function(i){var d={},g={},j=[],b=$("#planHeader").height();d.dockUndockViews=function(){var a,c=$(window).height(),e=$(window).scrollTop()-$("#pageWrapper").offset().top;$("#planHeader");var d=$("footer").is(":visible"),c=$(window).height(),i=$(window).scrollTop(),m=$("footer").offset().top;for(a in g)if(g.hasOwnProperty(a)){var h=g[a][0];if(-1===j.indexOf(a)&&h.is(":visible")){var f=g[a][1],k=f.dockTopAt&&f.dockTopAt.constructor&&f.dockTopAt.call&&
f.dockTopAt.apply?f.dockTopAt():f.dockTopAt,u=f.dockBottomAt&&f.dockBottomAt.constructor&&f.dockBottomAt.call&&f.dockBottomAt.apply?f.dockBottomAt():f.dockBottomAt,l=f.shouldDockBottom,s=f.canScroll,n=h.prop("scrollHeight"),q=f.contentHeight,t=f.scrollHeight,p=d?i+c-m:-1;0<p&&(q-=p);var q=n>q,v=e+b+n+23;f.subNav&&(v+=f.subNav.height());if(q&&!s)h.removeClass("dock-top"),h.removeClass("dock-bottom"),t||h.removeClass("scrollable");else if(e<k&&(0>p||!h.hasClass("scrollable")))t||h.removeClass("scrollable"),
h.removeClass("dock-top"),h.removeClass("dock-bottom"),h.css({"max-height":""});else if(l&&v>u)h.hasClass("dock-bottom")||(h.addClass("dock-bottom"),h.removeClass("dock-top"));else if(e>k||0<p)l=h.hasClass("dock-top"),l||(h.addClass("dock-top"),h.removeClass("dock-bottom")),e<k&&l&&h.removeClass("dock-top"),k=Math.min(c,u-e+23),k-=b,k-=23,k-=23,f.subNav&&(k-=f.subNav.height()),s&&(n>=k||q)?(0<p&&(k-=p),h.css({"max-height":k+"px"}),h.addClass("scrollable")):s&&h.hasClass("scrollable")&&(h.css({"max-height":""}),
h.removeClass("scrollable"))}}};d.dockView=function(a,b,e){e.dockBottomAt=void 0!==e.dockBottomAt?e.dockBottomAt:Number.MAX_VALUE;e.contentHeight=void 0!==e.contentHeight?e.contentHeight:Number.MAX_VALUE;e.shouldDockBottom=e.shouldDockBottom||!1;e.canScroll=e.canScroll||!1;g[a]=[b,e]};d.undockView=function(a){g[a]&&(g[a][0].removeClass("dock-top").removeClass("dock-bottom").removeClass("scrollable").css({"max-height":""}),delete g[a])};d.disableDock=function(a){-1===j.indexOf(a)&&j.push(a);g[a]&&
g[a][0].removeClass("dock-top").removeClass("dock-bottom").removeClass("scrollable").css({"max-height":""})};d.enableDock=function(a){a=j.indexOf(a);-1<a&&j.splice(a,1)};d.changeDockAttr=function(a,b){if(g[a])for(var e in b){var i=e,j=b[e];if(g[a]){var m=g[a][1];m.hasOwnProperty(i)&&(m[i]=j)}}d.dockUndockViews()};d.initialize=function(){i.addObserver("scroll","dock",d.dockUndockViews)};return d});
define("modules/view",["modules/events","modules/utils","modules/dock","jquery"],function(i,d){var g={},j;g.scrollCalendarElementIntoViewInModal=function(b,a,c){b=b instanceof jQuery?b:$(document.getElementById(b));b.length&&(a=c?c.parents(".dlg-show-overflow-calendar"):void 0,a=parseInt(a.css("padding-top"),10)+parseInt(a.css("top"),10),a=c.offset().top+a+c.find("#calendarBox .fc-head .fc-row thead").height()+c.find("#calendarStayBox").height(),b=b.offset().top-a,c.scrollTop(b))};g.scrollCalendarElementIntoView=
function(b,a){var c=b instanceof jQuery?b:$(document.getElementById(b));if(c.length){void 0===a&&(a=0);var e=$("#itinerarySubnavPane").outerHeight()+$("#planHeader").outerHeight()+$("#calendarBox .fc-head .fc-row thead").outerHeight()+$("#calendarStayBox").outerHeight(),c=c.offset().top-e+a,e=$("footer").offset().top-$(window).height(),c=Math.min(e,c);localStorage&&!localStorage.getItem("firstTimeLoadOfCalendarPage")?($("html").animate({scrollTop:c},"slow"),localStorage.setItem("firstTimeLoadOfCalendarPage",
!0)):window.scrollTo(0,c)}};g.scrollDayByDayElementIntoView=function(b,a){var c=b instanceof jQuery?b:$(document.getElementById(b));c.length&&(c=c.offset().top-$("#planHeader").height()-parseInt($("#itineraryMainPane").css("margin-top"))-parseInt($("#daybyday").css("margin-top"))+10,j=!0,$("html, body").animate({scrollTop:c},a?500:0,function(){j=!1}))};g.scrollElementIntoView=function(b,a,c,e){b=b instanceof jQuery?b:$(document.getElementById(b));if(b.length){void 0===a&&(a=0);var g=b.offset().left,
d=b.offset().top,i=b.offset().left+b.outerWidth(),h=b.offset().top+b.outerHeight(),f=window.pageXOffset,k=window.pageYOffset,u=window.pageXOffset+$(window).width(),l=window.pageYOffset+$(window).height();if(g>=f&&i<=u&&d>=k&&h<=l)e&&e();else if(g=0<$(".modal-box").length,b=b.offset().top,g&&(b+=$(".modal-box .ui-dialog-content").scrollTop()),a=b-10+a,j=!0,c)window.scrollTo(0,a),j=!1,e&&e();else{var s=!1;(g?$(".modal-box .ui-dialog-content"):$("html, body")).animate({scrollTop:a},500,function(){j=
!1;!s&&e&&(e(),s=!0)})}}};g.scrollAndUpdate=function(){i.triggerEvent("view","scroll",{manualScrollEvent:j})};g.initialize=function(){var b;if(b=window.addEventListener){var a=!1;try{var c=Object.defineProperty({},"passive",{get:function(){a=!0}});window.addEventListener("test",null,c)}catch(e){}b=a}b?window.addEventListener("scroll",function(){g.scrollAndUpdate()},{passive:!0}):$(window).scroll(function(){g.scrollAndUpdate()});d.enableMouseWheel();i.addObserver("scroll-first-visit","view",function(a,
b){b.$dialog?g.scrollCalendarElementIntoViewInModal(b.element,b.additionalYOffset,b.$dialog):g.scrollCalendarElementIntoView(b.element,b.additionalYOffset)})};return g});
define("modules/planTileEventRegister","modules/analytics modules/analyticsEventParams modules/events modules/ajax modules/utils seo/landing modules/view modules/lazyload jquery jqueryui".split(" "),function(i,d,g,j,b,a,c,e){function w(a){$(this).parents(".block").addClass("deleting");a.stopPropagation();return!1}function r(a){var b=$(this).parents(".block");$(this).parents(".duplicate").qtip("destroy");var e=a.data.from,h=a.data.analyticsCategory;if(!f){f=!0;var n=b.parents(".blocks"),q=b.data("planId"),
t=n.find(".block.plan");n.data("maxBlocks")&&t.length===parseInt(n.data("maxBlocks"))&&t.last().remove();var p=$('<div class="block loading"><div class="box"><span class="text in-box"><img class="progress-indicator" src="'+window.ajaxLoaderPath+'" alt="loading"><span class="primarytext">Duplicating...</span></span></div></div>');n.prepend(p);c.scrollElementIntoView(p,-120);j.makeAJAXcall({url:window.contextPath+"/duplicatePlan",data:{planId:q},type:"POST",success:function(a){var c;c=a.split("/");
for(var f,d=0;d<c.length;d++)if("plan"===c[d]){f=c[d+1];break}if(f){c=f.split("-");f=[];for(d=c.length-5;d<c.length;d++)f.push(c[d]);c=f.join("-")}else c=void 0;p.remove();d=b.clone(!0,!0);d.attr("href",a).css({opacity:0});d.attr("data-plan-id",c).data("planId",c);d.find(".updated span").text("LAST UPDATED: Less than a minute ago");window.isMobile?(a=$('<div class="col-12"></div>'),a.append(d),n.prepend(a)):n.prepend(d);d.animate({opacity:1},500);d.find(".delete svg").click(w);d.find(".duplicate svg").click({from:e,
analyticsCategory:h},r);window.isMobile||m(n.parents(".myplans,.myplans-main-pane"));a=n.parents(".myplans,.myplans-main-pane");d=a.data("numPlans");d+=1;a.attr("data-num-plans",d).data("numPlans",d);a.find(".myplans-title a, .plan-section .count, .page-title-area .count").text("("+d+")");g.triggerEvent(e,"plan-add",{numPlans:d})},complete:function(){f=!1}});i.trackEvent(h,d.ACT_DUP_PLAN)}a.stopPropagation();b.blur();return!1}function m(a){a.find(".duplicate").qtip({overwrite:!0,content:"DUPLICATE",
position:{my:"center right",at:"center left"},show:{event:"mouseover"},hide:{event:"mouseout",delay:50},style:{classes:"noShadow noBorder icon-tip"}})}var h={},f=!1;h.preparePlanTiles=function(c,f,l){l.off("click.newplan").on("click.newplan",".new-plan",function(){a.showPlanFormDialog({analyticsCategoryPrefix:f})}).off("click.block").on("click.block",".block",function(){if($(this).hasClass("deleting"))return!1}).off("click.cancel").on("click.cancel",".block .delete-conf .cancel",function(a){$(this).parents(".block").removeClass("deleting");
a.stopPropagation();return!1}).off("click.delete").on("click.delete",".block .delete",function(a){$(this).parents(".block").addClass("deleting");a.stopPropagation();return!1}).off("click.confdelete").on("click.confdelete",".block .confirm",function(a){$(this).attr("disabled","disabled").text("Deleting...");var b=$(this).parents(".block"),e=b.data("planId"),m=(b=b.data("owner"))?d.ACT_DEL_PLAN:d.ACT_DEL_SHARED_PLAN;j.makeAJAXcall({url:b?window.contextPath+"/trip/"+e+"/delete":window.contextPath+"/user/sharedplans/"+
e+"/delete",type:"POST",data:{view:c},success:function(a){a=$(a||"<div></div>");l.html(a.html());a=a.data("numPlans");l.attr("data-num-plans",a).data("numPlans",a);g.triggerEvent(c,"plan-delete",{numPlans:a});i.trackEvent(f,m,"",function(){"myPlans"===c&&0===l.find(".block").length?window.location=window.contextPath+"/":0===l.find(".block").length?window.location.reload():h.preparePlanTiles(c,f,l)})}});a.stopPropagation();return!1}).off("click.plan").on("click.plan",".block",function(a){var b=$(this).attr("href");
if(b)return i.trackEvent(f,"plan-tile-click",null,function(){window.location=b}),a.stopPropagation(),!1});l.find(".delete svg").click(w);l.find(".duplicate svg").click({from:c,analyticsCategory:f},r);window.isMobile||m(l);b.ellipsizePlanNames($(".block.plan"));navigator.userAgent.match(/(iPhone|iPod|iPad|Android|BlackBerry)/)&&l.find(".plan.block").addClass("tablet");e.initialize()};return h});
require(["jquery","jqueryui"],function(){$.widget("ui.dialog",$.ui.dialog,{_create:function(){this.options.closeText="";setTimeout(function(){$("body").addClass("dummy").removeClass("dummy")},1);return this._super()},_title:function(i){this.options.title?i.html(this.options.title):i.html("&#160;")}})});define("jqueryuioverrides",function(){});
require("modules/analytics modules/analyticsEventParams modules/header modules/events seo/landing modules/lazyload modules/planTileEventRegister jquery jqueryui jqueryuioverrides qtip jQueryExtensions/inspirockAutocomplete".split(" "),function(i,d,g,j,b,a,c){var e={initialize:function(){i.setPageType("Home Page");i.setProperty("page","/home");i.trackPageView("/home");j.triggerEvent("home","mmt_track_page",{channel:"inspirock",page:"Landing:Inspirock"});b.prepareHeader($(".hero").outerHeight());$(".trending").off("click.destination").on("click.destination",
".block.destination",function(){var a=$(this);i.trackEvent(d.CAT_HP_TRENDING,d.ACT_DEST_CLICK,void 0,function(){window.location=a.attr("href")});return!1}).off("click.info").on("click.info",".block.info",function(){var a=$(this);i.trackEvent(d.CAT_HP_TRENDING,d.ACT_RECENT_PLANS_CLICK,void 0,function(){window.location=a.attr("href")});return!1}).off("click.plan").on("click.plan",".block.plan",function(){var a=$(this),b=d.CAT_HP_TRENDING;a.parents(".trending").hasClass("recent-plans")?b=d.CAT_HP_RECENTPLANS:
a.parents(".trending").hasClass("suggested-plans")&&(b=d.CAT_HP_SUGGESTEDPLANS);i.trackEvent(b,d.ACT_PLAN_CLICK,void 0,function(){window.location=a.attr("href")});return!1});$(".myplans").off("click.newplan").on("click.newplan",".newplan",function(){b.showPlanFormDialog({analyticsCategoryPrefix:"home.myplans.newplan"})});$(".travel-hub").off("click.cta").on("click.cta",".cta-button",function(){b.showPlanFormDialog({analyticsCategoryPrefix:"home.travelhub"})});c.preparePlanTiles("home",d.CAT_HP_MYPLANS,
$(".myplans"));var e=[{id:void 0,label:"Popular Destinations",nightstay:!1,value:void 0,selectable:!1,li:"<li>Popular Destinations</li>",className:"section-title"}];$(".home-form").find(".popular-destinations").children("li").each(function(){var a=$(this),b=a.data("id"),a=a.data("label");e.push({id:b,label:a,value:a,selectable:!0,li:"<li>"+a+"</li>",className:"indent1"})});$(".planning-form").preparePlanForm("home-form",$("#progress-indicator"),$("#home-shade"),null,e);var r=$(".stickers").find(".sticker");
1!==r.length&&window.setInterval(function(){var a=r.filter(".active"),b=(a.index()+1)%r.length;a.removeClass("active");r.eq(b).addClass("active")},7E3);var m=$(".hero-image-wrap .hero-image");1!==m.length&&window.setInterval(function(){var a=m.filter(".active"),b=(a.index()+1)%m.length;a.removeClass("active");m.eq(b).addClass("active")},13E3);var h=$(".press-row"),f=h.children(".press");h.off("click.prev").on("click.prev",".prev",function(){if(!f.find(".press-logo").first().is(":animated")){var a=
f.find(".press-logo").last();a.css({marginLeft:"-"+f.width()/5+"px"});a.prependTo(f);a.animate({marginLeft:0})}});h.off("click.next").on("click.next",".next",function(){var a=f.find(".press-logo").first();a.is(":animated")||a.animate({marginLeft:"-"+f.width()/5+"px"},function(){a.appendTo(f);a.css({marginLeft:0})})});g.initialize();a.initialize({onscroll:!0});var k=$("#home-planning-form");if(k.length)$("#newplan").off("click").on("click",function(){$("#home-shade").fadeIn(250);$("body,html").animate({scrollTop:k.offset().top-
150},500);return!1})}};e.initialize();return e});define("home",function(){});