/* 
 *  Copyright (c) 2012-2017, Inspirock Corporation.
 *  All rights reserved.
 */

/* 
 *  Copyright (c) 2012-2014, Inspirock Corporation.
 *  All rights reserved.
 */

require(["jquery","jqueryui"],function(){$.widget("ui.dialog",$.ui.dialog,{_create:function(){this.options.closeText="";setTimeout(function(){$("body").addClass("dummy").removeClass("dummy")},1);return this._super()},_title:function(g){this.options.title?g.html(this.options.title):g.html("&#160;")}})});define("jqueryuioverrides",function(){});
require("modules/analytics modules/analyticsEventParams modules/utils modules/header modules/ajax modules/fbutil modules/events jquery jqueryui jqueryuioverrides qtip".split(" "),function(g,m,c,y,n,z,A){function j(a,b){if(a.is("input:text"))a.off("input.errorhide click.errorhide").on("input.errorhide click.errorhide",function(){i(a)});else if(a.is("input:password"))a.off("input click").on("input click",function(){i(a)});a.qtip({content:{text:b},show:{ready:!0},hide:{event:"unfocus",fixed:!0},position:{my:"left center",
at:"right center",viewport:$("body"),container:$("body"),effect:!1},style:{classes:"qtip-light qtip-shadow signup-error-tip",tip:{corner:!0,width:15,height:10}}})}function i(a){a.qtip("destroy");window.isMobile&&a.removeClass("has-error")}function t(a){$("#loginPasswordError").html(a);$(".login-error-container").removeClass("hidden");$(".login").addClass("login-error");a=$('<div class="text-check">Are you using your Inspirock Trip<br/> Planner username and password?</div><div class="text-info">Inspirock Trip Planner requires a separate login</div>');
$(".login-error-container").hasClass("partner-error")&&q($("#loginPasswordError"),a,"invalid-user",-45);$("#loginUsername,#loginPassword").off("input").on("input",function(){$(".login-error-container").addClass("hidden");$(".login").removeClass("login-error");$("#loginPasswordError").html("");$("#loginUsername,#loginPassword").off("input")})}function B(){$(".qtip").qtip("destroy");n.makeAJAXcall({type:"POST",url:window.contextPath+"/resendVerificationEmail",data:{username:k.find("#loginUsername").val().trim(),
partner:c.getParameterByName("partner")},success:function(a){"SUCCESS"===a.status&&a.additionalData.emailSent&&c.showOkDialog("Email Sent","An email with account verification details has been sent again.","OK")}})}function C(a){13===a.keyCode&&(a.stopPropagation(),u())}function D(){var a=$("#signupPassword"),b=a.val().trim(),e=null;if(0===b.length)a.removeClass("weak medium"),c.hideErrorTooltip(a);else{if(8>b.length)e="weak";else if(!b.match(/[A-Z]/)||!b.match(/[a-z]/)||!b.match(/[0-9]/))e="medium";
a.removeClass("weak medium");e?(c.showErrorTooltip(a,"Strong passwords are at least 8 characters in length and contain at least 1 lowercase, 1 uppercase, and 1 numeric character.",void 0,{style:{classes:"info signup-error-tip"},position:{my:"left center",at:"right center",container:a.parents("#loginPage"),viewport:$(window),effect:!1}}),a.addClass(e)):c.hideErrorTooltip(a)}}function E(a){13===a.keyCode&&(a.stopPropagation(),v())}function F(){var a=$(this).val().trim(),b=$("#signupFirstName"),e=$("#signupLastName"),
d;c.validateEmail(a)&&(0===b.val().trim().length&&0===e.val().trim().length)&&(d=a.split("@")[0].split(/[._\-]/),1===d.length?(a=d[0].charAt(0).toUpperCase()+d[0].slice(1),b.val(a).data("autofill",a),e.val("").data("autofill","")):(a=d[0].charAt(0).toUpperCase()+d[0].slice(1),d=d[1].charAt(0).toUpperCase()+d[1].slice(1),b.val(a).data("autofill",a),e.val(d).data("autofill",d)))}function G(){var a=c.getParameterByName("post-login-url"),a=a?a:window.contextPath,b=c.getParameterByName("partner"),e=c.getParameterByName("partnerUserId"),
a={"post-login-url":a,partner:b,partnerUserId:e};h(!0,"Logging in...");n.makeAJAXcall({type:"POST",data:a,url:window.contextPath+"/continueLoggedIn",success:function(a){"SUCCESS"===a.status?a.redirectUrl&&g.trackEvent(m.CAT_LOGIN_CONTINUE,"login","",function(){window.location.href=a.redirectUrl}):a.redirectUrl?window.location.href=a.redirectUrl:h(!1)}})}function H(){g.trackEvent(m.CAT_LOGIN,"logout","native",function(){$("#loginPageLogoutForm").submit()})}function q(a,b,c,d){a.qtip({content:{text:b},
show:{event:"click mouseenter"},hide:{delay:50,fixed:!0},position:{my:"left center",at:"right center",adjust:{x:10,method:"flip"}},style:{classes:"error-qtip qtip-light qtip-shadow login-tip "+c,tip:{corner:!0,offset:d,width:20,height:10,mimic:"left center"}}})}var r={},l,k,f,s,h=function(a,b){var c=l.find(".card:visible").find(".login-progress");void 0!==b&&c.find(".progress-txt").text(b);!0===a?(c.siblings().css({opacity:0}),c.removeClass("hidden")):(c.siblings().css({opacity:1}),c.addClass("hidden"))},
I=function(){$(".qtip").qtip("destroy");h(!0,"Logging in...");var a=c.getParameterByName("post-login-url"),b=c.getParameterByName("partner"),e=c.getParameterByName("partnerUserId"),d=c.getParameterByName("rerequest"),a=a?a:window.contextPath;z.loginToFB("login",function(a){"connected"!==a&&h(!1)},{"post-login-url":a,partner:b,partnerUserId:e,rerequest:d})},v=function(){var a;a:{var b=f;a=b.find("#signupUsername");var e=b.find("#signupPassword"),d=b.find("#signupConfirmPassword"),p=b.find("#signupFirstName"),
b=b.find("#signupLastName"),w=!0;if(0===a.val().trim().length)j(a,"E-mail address must be provided.");else if(c.validateEmail(a.val().trim()))if(i(a),p.val().trim().length)if(c.isName(p.val().trim()))if(i(p),b.val().trim().length){if(c.isName(b.val().trim())){i(b);0===e.val().trim().length?(w=!1,j(e,"Password must be provided.")):(i(e),i(d));a=w;break a}j(b,"Last name cannot contain any numbers or special characters.")}else j(b,"Last name must be provided.");else j(p,"First name cannot contain any numbers or special characters.");
else j(p,"First name must be provided."),i(b);else j(a,"E-mail address is not valid.");a=void 0}a&&(a=(a=c.getParameterByName("post-login-url"))?a:window.contextPath,e=c.getParameterByName("partner"),d=c.getParameterByName("partnerUserId"),a={username:f.find("#signupUsername").val(),password:f.find("#signupPassword").val(),firstname:f.find("#signupFirstName").val(),lastname:f.find("#signupLastName").val(),"post-login-url":a,partner:e,partnerUserId:d},$(".qtip").qtip("destroy",!0),h(!0,"Registering..."),
n.makeAJAXcall({type:"POST",data:a,url:window.contextPath+"/inspirockRegistration",success:function(a){h(!1);if("SUCCESS"===a.status){g.trackEvent(m.CAT_LOGIN,"registration","native");window.goog_report_conversion&&window.goog_report_conversion("pQY0CMvCtmgQlJfm7QM",0.01);var b=function(){window.location.href=a.redirectUrl};c.showOkDialog("You are all set!",a.message,"OK",b,b)}else if(a.redirectUrl)window.location.href=a.redirectUrl;else{var d="";for(b in a.errors)d+=a.errors[b].error+"<br />";f.find(".error-message").html(d);
f.find(".signup").addClass("signup-error");$("#signupUsername, #signupPassword").off("input").on("input",function(){f.find(".signup").removeClass("signup-error");f.find(".error-message").html("")})}}}))},u=function(){var a=c.getParameterByName("post-login-url"),a=a?a:window.contextPath,b=c.getParameterByName("partner"),e=c.getParameterByName("partnerUserId"),a={username:k.find("#loginUsername").val().trim(),password:k.find("#loginPassword").val().trim(),rememberMe:k.find("#rememberMe").prop("checked"),
"post-login-url":a,partner:b,partnerUserId:e};!a.username||!a.password?t("Please enter your email Id and Password."):($(".qtip").qtip("destroy"),h(!0,"Logging in..."),n.makeAJAXcall({type:"POST",data:a,url:window.contextPath+"/inspirockLogin",success:function(a){if("SUCCESS"===a.status)a.redirectUrl&&g.trackEvent(m.CAT_LOGIN,"login","native",function(){window.location.href=a.redirectUrl});else if(a.redirectUrl)window.location.href=a.redirectUrl;else{h(!1);for(var b=0,b=0;b<a.errors.length;b++){var e=
a.errors[b];e.field?c.showErrorTooltip(k.find("#"+e.field),e.error,function(){$(this).off("click.resendVerification").on("click.resendVerification",".resend-verification",B)}):t(e.error)}}}}))},J=function(){var a=$(this),b=s.find("#resetemail"),e=b.val().trim(),d=!0;0===e.length?(d=!1,c.showErrorTooltip(b,"E-mail address must be provided.")):c.hideErrorTooltip(b);if(d){var d=(d=c.getParameterByName("post-login-url"))?d:window.contextPath,f=c.getParameterByName("partner");a.attr("disabled","disabled");
n.makeAJAXcall({type:"POST",data:{email:e,"post-login-url":d,partner:f},url:window.contextPath+"/forgotPassword",success:function(a){a=$.parseJSON(a);a.error?c.showErrorTooltip(b,a.error):(c.showOkDialog("Check your email","OK, we just sent you an email message. Inside that message is a link you can use to change your password.<br/><br/>The message should show up within a few seconds. If it doesn't, check your spam or junk mail folder.","OK"),g.trackEvent(m.CAT_LOGIN,"forgot-password"),x())},complete:function(){a.removeAttr("disabled")}})}},
x=function(){k.removeClass("hidden").siblings().addClass("hidden");$(".qtip").qtip("destroy");q($(".help-icon"),"Our groundbreaking Trip Planner<br/> is powered by Inspirock, which<br/> requires a separate login","login-help",-30)},K=function(){f.removeClass("hidden").siblings().addClass("hidden");$(".qtip").qtip("destroy");q($(".help-icon"),"Our groundbreaking Trip Planner is powered by Inspirock, which requires a sign up or a login with Facebook","signup-help",-40)},L=function(){s.removeClass("hidden").siblings().addClass("hidden");
$(".qtip").qtip("destroy")};r.initialize=function(){l=$("#loginPage");k=l.find("#login");f=l.find("#registration");s=l.find("#forgotpassword");l.off("click.fbLogin").on("click.fbLogin",".fb-login",I).off("click.toLogin").on("click.toLogin",".to-login",x).off("click.toSignUp").on("click.toSignUp",".to-signup",K).off("click.toReset").on("click.toReset",".to-reset",L).off("click.login").on("click.login",".login",u).off("click.signup").on("click.signup",".signup",v).off("click.reset").on("click.reset",
".reset",J).off("click.continue").on("click.continue",".continue",G).off("click.logout").on("click.logout",".logout",H).off("keydown.login").on("keydown.login","#login input",C).off("keydown.signup").on("keydown.signup","#registration input",E).off("keyup.signup").on("keyup.signup","#signupPassword",D).off("blur.signupEmail").on("blur.signupEmail","#signupUsername",F);l.find("#flash").click(function(){$(this).hide()});var a=c.getParameterByName("defaultView"),b=c.getParameterByName("reason"),e=c.getParameterByName("error");
("processLoginData"===a||b||e)&&g.setReferrer(location.origin);g.setPageType("Login Page");g.trackPageView();A.triggerEvent("home","mmt_track_page",{channel:"inspirock",page:"Login:Inspirock"});y.initialize();if("processLoginData"===c.getParameterByName("defaultView")){var a=$("#processLoginData"),d=a.data("postLoginUrl");h(!0);a.data("firstname");a.data("lastname");a.data("email");a.data("userId");c.getParameterByName("action");g.trackEvent(m.CAT_LOGIN,c.getParameterByName("action"),"facebook",function(){d&&
(window.location.href=d)})}q($(".help-icon"),"Our groundbreaking Trip Planner<br/> is powered by Inspirock, which<br/> requires a separate login","login-help",-30)};r.initialize();return r});define("login",function(){});